@startuml
hide empty description
scale 350 width
[*] --> 関数
配列と繰り返し --> 初等的整列
配列と繰り返し --> スタック
配列と繰り返し --> キュー
構造体とポインタ --> リスト
配列と繰り返し --> 線形探索
配列と繰り返し --> 二分探索
配列と繰り返し --> ハッシュ

関数 --> 再帰関数
再帰関数 --> 分割統治法

初等的整列 --> パーティション
パーティション --> 高等的整列
分割統治法 --> 高等的整列

配列と構造体 --> 木構造
木構造 --> 二分木
二分木 --> 木の巡回
再帰関数 --> 木の巡回

二分木 --> 二分探索木
リスト --> 二分探索木

配列 --> 完全二分木
完全二分木 --> 二分ヒープ
二分ヒープ --> 優先度付きキュー
キュー --> 優先度付きキュー

配列 --> 動的計画法:1次元
動的計画法:1次元 --> 動的計画法:多次元
多次元配列 --> 動的計画法:多次元
動的計画法:多次元 --> 最長共通部分列
動的計画法:多次元 --> 連鎖行列積

再帰関数 --> 深さ優先探索
スタック --> 深さ優先探索
キュー --> 幅優先探索
多次元配列 --> グラフ隣接行列
グラフ隣接行列 --> 深さ優先探索
グラフ隣接行列 --> 幅優先探索
グラフ隣接行列 --> グラフ隣接リスト
リスト --> グラフ隣接リスト
深さ優先探索 --> 連結成分分解
幅優先探索 --> 連結成分分解
グラフ隣接リスト --> 連結成分分解

グラフ --> 最小全域木
最小全域木 --> 最短経路
最短経路 --> p最短経路
優先度付きキュー --> p最短経路

木構造 --> UnionFind
高等的整列 --> 領域探索
二分探索木 --> 領域探索
木の巡回 --> 領域探索

グラフ隣接行列 --> 全点対間最短経路
動的計画法:多次元 --> 全点対間最短経路
深さ優先探索 --> 関節点
深さ優先探索 --> トポロジカルソート
幅優先探索 --> トポロジカルソート
高等的整列 --> 最小全域木
UnionFind --> 最小全域木


分割統治法 --> [*]
@enduml